# generated by datamodel-codegen:
#   filename:  dograh-openapi-XXXXXX.json.wRbj3k1Uly
#   timestamp: 2026-05-17T13:13:13+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ARIConfigurationRequest(BaseModel):
    """
    Request schema for Asterisk ARI configuration.
    """

    provider: Annotated[Literal['ari'], Field(title='Provider')] = 'ari'
    ari_endpoint: Annotated[str, Field(title='Ari Endpoint')]
    """
    ARI base URL (e.g., http://asterisk.example.com:8088)
    """
    app_name: Annotated[str, Field(title='App Name')]
    """
    Stasis application name registered in Asterisk
    """
    app_password: Annotated[str, Field(title='App Password')]
    """
    ARI user password
    """
    ws_client_name: Annotated[str | None, Field(title='Ws Client Name')] = ''
    """
    websocket_client.conf connection name for externalMedia (e.g., dograh_staging)
    """
    from_numbers: Annotated[list[str] | None, Field(title='From Numbers')] = None
    """
    List of SIP extensions/numbers for outbound calls (optional)
    """


class CalculatorToolDefinition(BaseModel):
    """
    Tool definition for Calculator tools (no configuration needed).
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version
    """
    type: Annotated[Literal['calculator'], Field(title='Type')]
    """
    Tool type
    """


class CallDispositionCodes(BaseModel):
    disposition_codes: Annotated[list[str] | None, Field(title='Disposition Codes')] = (
        []
    )


class CampaignLogEntryResponse(BaseModel):
    """
    A single timestamped entry from the campaign's append-only log.

    Surfaced in the UI so operators can see why a campaign moved to
    paused / failed without digging through server logs.
    """

    ts: Annotated[str, Field(title='Ts')]
    level: Annotated[str, Field(title='Level')]
    event: Annotated[str, Field(title='Event')]
    message: Annotated[str, Field(title='Message')]
    details: Annotated[dict[str, Any] | None, Field(title='Details')] = None


class CampaignProgressResponse(BaseModel):
    campaign_id: Annotated[int, Field(title='Campaign Id')]
    state: Annotated[str, Field(title='State')]
    total_rows: Annotated[int, Field(title='Total Rows')]
    processed_rows: Annotated[int, Field(title='Processed Rows')]
    failed_calls: Annotated[int, Field(title='Failed Calls')]
    progress_percentage: Annotated[float, Field(title='Progress Percentage')]
    source_sync: Annotated[dict[str, Any], Field(title='Source Sync')]
    rate_limit: Annotated[int, Field(title='Rate Limit')]
    started_at: Annotated[AwareDatetime | None, Field(title='Started At')]
    completed_at: Annotated[AwareDatetime | None, Field(title='Completed At')]


class CampaignRunsResponse(BaseModel):
    """
    Paginated response for campaign workflow runs
    """

    runs: Annotated[list[dict[str, Any]], Field(title='Runs')]
    total_count: Annotated[int, Field(title='Total Count')]
    page: Annotated[int, Field(title='Page')]
    limit: Annotated[int, Field(title='Limit')]
    total_pages: Annotated[int, Field(title='Total Pages')]


class CampaignSourceDownloadResponse(BaseModel):
    download_url: Annotated[str, Field(title='Download Url')]
    expires_in: Annotated[int, Field(title='Expires In')]


class ChunkResponseSchema(BaseModel):
    """
    Response schema for a document chunk.
    """

    id: Annotated[int, Field(title='Id')]
    document_id: Annotated[int, Field(title='Document Id')]
    chunk_text: Annotated[str, Field(title='Chunk Text')]
    contextualized_text: Annotated[str | None, Field(title='Contextualized Text')]
    chunk_index: Annotated[int, Field(title='Chunk Index')]
    chunk_metadata: Annotated[dict[str, Any], Field(title='Chunk Metadata')]
    filename: Annotated[str, Field(title='Filename')]
    document_uuid: Annotated[str, Field(title='Document Uuid')]
    similarity: Annotated[float, Field(title='Similarity')]


class MinSimilarity(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=1.0, title='Min Similarity')]
    """
    Minimum similarity threshold
    """


class ChunkSearchRequestSchema(BaseModel):
    """
    Request schema for searching similar chunks.
    """

    query: Annotated[str, Field(title='Query')]
    """
    Search query text
    """
    limit: Annotated[int | None, Field(ge=1, le=50, title='Limit')] = 5
    """
    Maximum number of results
    """
    document_uuids: Annotated[list[str] | None, Field(title='Document Uuids')] = None
    """
    Filter by specific document UUIDs
    """
    min_similarity: Annotated[MinSimilarity | None, Field(title='Min Similarity')] = (
        None
    )
    """
    Minimum similarity threshold
    """


class ChunkSearchResponseSchema(BaseModel):
    """
    Response schema for chunk search results.
    """

    chunks: Annotated[list[ChunkResponseSchema], Field(title='Chunks')]
    query: Annotated[str, Field(title='Query')]
    total_results: Annotated[int, Field(title='Total Results')]


class CircuitBreakerConfigRequest(BaseModel):
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    failure_threshold: Annotated[
        float | None, Field(ge=0.0, le=1.0, title='Failure Threshold')
    ] = 0.5
    window_seconds: Annotated[
        int | None, Field(ge=30, le=600, title='Window Seconds')
    ] = 120
    min_calls_in_window: Annotated[
        int | None, Field(ge=1, le=100, title='Min Calls In Window')
    ] = 5


class CircuitBreakerConfigResponse(BaseModel):
    enabled: Annotated[bool | None, Field(title='Enabled')] = False
    failure_threshold: Annotated[float | None, Field(title='Failure Threshold')] = 0.5
    window_seconds: Annotated[int | None, Field(title='Window Seconds')] = 120
    min_calls_in_window: Annotated[int | None, Field(title='Min Calls In Window')] = 5


class CloudonixConfigurationRequest(BaseModel):
    """
    Request schema for Cloudonix configuration.
    """

    provider: Annotated[Literal['cloudonix'], Field(title='Provider')] = 'cloudonix'
    bearer_token: Annotated[str, Field(title='Bearer Token')]
    """
    Cloudonix API Bearer Token
    """
    domain_id: Annotated[str, Field(title='Domain Id')]
    """
    Cloudonix Domain ID
    """
    application_name: Annotated[str | None, Field(title='Application Name')] = None
    """
    Cloudonix Voice Application name. The application's url is updated when inbound workflows are attached to numbers on this domain. If omitted, an application is auto-created on save and its name is stored on the configuration.
    """
    from_numbers: Annotated[list[str] | None, Field(title='From Numbers')] = None
    """
    List of Cloudonix phone numbers (optional)
    """


class MaxConcurrency(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=100, title='Max Concurrency')]


class Icon(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Icon')] = 'globe'


class IconColor(RootModel[str]):
    root: Annotated[str, Field(max_length=7, title='Icon Color')] = '#3B82F6'


class CreateWorkflowRequest(BaseModel):
    name: Annotated[str, Field(title='Name')]
    workflow_definition: Annotated[dict[str, Any], Field(title='Workflow Definition')]


class CreatedByResponse(BaseModel):
    """
    Response schema for the user who created a tool.
    """

    id: Annotated[int, Field(title='Id')]
    provider_id: Annotated[str, Field(title='Provider Id')]


class CredentialResponse(BaseModel):
    """
    Response schema for a webhook credential (never includes sensitive data).
    """

    uuid: Annotated[str, Field(title='Uuid')]
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')]
    credential_type: Annotated[str, Field(title='Credential Type')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime | None, Field(title='Updated At')]


class DailyReportResponse(BaseModel):
    date: Annotated[str, Field(title='Date')]
    timezone: Annotated[str, Field(title='Timezone')]
    workflow_id: Annotated[int | None, Field(title='Workflow Id')]
    metrics: Annotated[dict[str, int], Field(title='Metrics')]
    disposition_distribution: Annotated[
        list[dict[str, Any]], Field(title='Disposition Distribution')
    ]
    call_duration_distribution: Annotated[
        list[dict[str, Any]], Field(title='Call Duration Distribution')
    ]


class DisplayOptions(BaseModel):
    """
    Conditional visibility rules.

    `show` keys are AND-combined: this property is visible only when EVERY
    referenced field's value matches one of the listed values.

    `hide` keys are OR-combined: this property is hidden when ANY referenced
    field's value matches one of the listed values.

    Example:
        DisplayOptions(show={"extraction_enabled": [True]})
        DisplayOptions(show={"greeting_type": ["audio"]})
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    show: Annotated[dict[str, list[Any]] | None, Field(title='Show')] = None
    hide: Annotated[dict[str, list[Any]] | None, Field(title='Hide')] = None


class DocumentResponseSchema(BaseModel):
    """
    Response schema for document metadata.
    """

    id: Annotated[int, Field(title='Id')]
    document_uuid: Annotated[str, Field(title='Document Uuid')]
    filename: Annotated[str, Field(title='Filename')]
    file_size_bytes: Annotated[int, Field(title='File Size Bytes')]
    file_hash: Annotated[str, Field(title='File Hash')]
    mime_type: Annotated[str, Field(title='Mime Type')]
    processing_status: Annotated[str, Field(title='Processing Status')]
    processing_error: Annotated[str | None, Field(title='Processing Error')] = None
    total_chunks: Annotated[int, Field(title='Total Chunks')]
    retrieval_mode: Annotated[str | None, Field(title='Retrieval Mode')] = 'chunked'
    custom_metadata: Annotated[dict[str, Any], Field(title='Custom Metadata')]
    docling_metadata: Annotated[dict[str, Any], Field(title='Docling Metadata')]
    source_url: Annotated[str | None, Field(title='Source Url')] = None
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    organization_id: Annotated[int, Field(title='Organization Id')]
    created_by: Annotated[int, Field(title='Created By')]
    is_active: Annotated[bool, Field(title='Is Active')]


class DocumentUploadRequestSchema(BaseModel):
    """
    Request schema for initiating document upload.
    """

    filename: Annotated[str, Field(title='Filename')]
    """
    Name of the file to upload
    """
    mime_type: Annotated[str, Field(title='Mime Type')]
    """
    MIME type of the file
    """
    custom_metadata: Annotated[
        dict[str, Any] | None, Field(title='Custom Metadata')
    ] = None
    """
    Optional custom metadata
    """


class DocumentUploadResponseSchema(BaseModel):
    """
    Response schema containing upload URL and document metadata.
    """

    upload_url: Annotated[str, Field(title='Upload Url')]
    """
    Signed URL for uploading the file
    """
    document_uuid: Annotated[str, Field(title='Document Uuid')]
    """
    Unique identifier for the document
    """
    s3_key: Annotated[str, Field(title='S3 Key')]
    """
    S3 key where file should be uploaded
    """


class EmbedTokenRequest(BaseModel):
    allowed_domains: Annotated[list[str] | None, Field(title='Allowed Domains')] = None
    settings: Annotated[dict[str, Any] | None, Field(title='Settings')] = None
    usage_limit: Annotated[int | None, Field(title='Usage Limit')] = None
    expires_in_days: Annotated[int | None, Field(title='Expires In Days')] = 30


class EmbedTokenResponse(BaseModel):
    id: Annotated[int, Field(title='Id')]
    token: Annotated[str, Field(title='Token')]
    allowed_domains: Annotated[list[str] | None, Field(title='Allowed Domains')]
    settings: Annotated[dict[str, Any] | None, Field(title='Settings')]
    is_active: Annotated[bool, Field(title='Is Active')]
    usage_count: Annotated[int, Field(title='Usage Count')]
    usage_limit: Annotated[int | None, Field(title='Usage Limit')]
    expires_at: Annotated[AwareDatetime | None, Field(title='Expires At')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    embed_script: Annotated[str, Field(title='Embed Script')]


class MessageType(Enum):
    """
    Type of goodbye message
    """

    none = 'none'
    custom = 'custom'
    audio = 'audio'


class EndCallConfig(BaseModel):
    """
    Configuration for End Call tools.
    """

    messageType: Annotated[MessageType | None, Field(title='Messagetype')] = 'none'
    """
    Type of goodbye message
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before ending the call
    """
    audioRecordingId: Annotated[str | None, Field(title='Audiorecordingid')] = None
    """
    Recording ID for audio goodbye message
    """
    endCallReason: Annotated[bool | None, Field(title='Endcallreason')] = False
    """
    When enabled, LLM must provide a reason for ending the call. The reason is set as call disposition and added to call tags.
    """
    endCallReasonDescription: Annotated[
        str | None, Field(title='Endcallreasondescription')
    ] = None
    """
    Description shown to the LLM for the reason parameter. Used only when endCallReason is enabled.
    """


class EndCallToolDefinition(BaseModel):
    """
    Tool definition for End Call tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version
    """
    type: Annotated[Literal['end_call'], Field(title='Type')]
    """
    Tool type
    """
    config: EndCallConfig
    """
    End Call configuration
    """


class FileDescriptor(BaseModel):
    """
    Descriptor for a single file in a batch upload request.
    """

    filename: Annotated[str, Field(title='Filename')]
    """
    Original filename of the audio file
    """
    mime_type: Annotated[str | None, Field(title='Mime Type')] = 'audio/wav'
    """
    MIME type of the audio file
    """
    file_size: Annotated[int, Field(gt=0, le=5242880, title='File Size')]
    """
    File size in bytes (max 5MB)
    """


class GraphConstraints(BaseModel):
    """
    Per-node-type graph rules. WorkflowGraph enforces these at validation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    min_incoming: Annotated[int | None, Field(title='Min Incoming')] = None
    max_incoming: Annotated[int | None, Field(title='Max Incoming')] = None
    min_outgoing: Annotated[int | None, Field(title='Min Outgoing')] = None
    max_outgoing: Annotated[int | None, Field(title='Max Outgoing')] = None


class CustomMessageType(Enum):
    """
    Type of custom message: text or audio
    """

    text = 'text'
    audio = 'audio'


class InitiateCallRequest(BaseModel):
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    workflow_run_id: Annotated[int | None, Field(title='Workflow Run Id')] = None
    phone_number: Annotated[str | None, Field(title='Phone Number')] = None
    telephony_configuration_id: Annotated[
        int | None, Field(title='Telephony Configuration Id')
    ] = None
    from_phone_number_id: Annotated[int | None, Field(title='From Phone Number Id')] = (
        None
    )


class NodeCategory(Enum):
    """
    Drives grouping in the AddNodePanel UI.
    """

    call_node = 'call_node'
    global_node = 'global_node'
    trigger = 'trigger'
    integration = 'integration'


class NodeExample(BaseModel):
    """
    A worked example LLMs can pattern-match. Keep small and realistic.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')] = None
    data: Annotated[dict[str, Any], Field(title='Data')]


class CountryCode(RootModel[str]):
    root: Annotated[str, Field(max_length=2, min_length=2, title='Country Code')]


class Label(RootModel[str]):
    root: Annotated[str, Field(max_length=64, title='Label')]


class PhoneNumberCreateRequest(BaseModel):
    """
    Create a new phone number under a telephony configuration.

    ``address_normalized`` and ``address_type`` are computed server-side from
    ``address`` (and ``country_code`` if PSTN). ``address`` itself is stored
    verbatim for display.
    """

    address: Annotated[str, Field(max_length=255, min_length=1, title='Address')]
    country_code: Annotated[CountryCode | None, Field(title='Country Code')] = None
    label: Annotated[Label | None, Field(title='Label')] = None
    inbound_workflow_id: Annotated[int | None, Field(title='Inbound Workflow Id')] = (
        None
    )
    is_active: Annotated[bool | None, Field(title='Is Active')] = True
    is_default_caller_id: Annotated[
        bool | None, Field(title='Is Default Caller Id')
    ] = False
    extra_metadata: Annotated[dict[str, Any] | None, Field(title='Extra Metadata')] = (
        None
    )


class PlivoConfigurationRequest(BaseModel):
    """
    Request schema for Plivo configuration.
    """

    provider: Annotated[Literal['plivo'], Field(title='Provider')] = 'plivo'
    auth_id: Annotated[str, Field(title='Auth Id')]
    """
    Plivo Auth ID
    """
    auth_token: Annotated[str, Field(title='Auth Token')]
    """
    Plivo Auth Token
    """
    application_id: Annotated[str | None, Field(title='Application Id')] = None
    """
    Plivo Application ID. The application's answer_url is updated when inbound workflows are attached to numbers on this account. If omitted, an application is auto-created on save and its id is stored on the configuration.
    """
    from_numbers: Annotated[list[str] | None, Field(title='From Numbers')] = None
    """
    List of Plivo phone numbers
    """


class ProcessDocumentRequestSchema(BaseModel):
    """
    Request schema for triggering document processing.
    """

    document_uuid: Annotated[str, Field(title='Document Uuid')]
    """
    Document UUID to process
    """
    s3_key: Annotated[str, Field(title='S3 Key')]
    """
    S3 key of the uploaded file
    """
    retrieval_mode: Annotated[str | None, Field(title='Retrieval Mode')] = 'chunked'
    """
    Retrieval mode: 'chunked' for vector search or 'full_document' for full text retrieval
    """


class PropertyOption(BaseModel):
    """
    An option in an `options` or `multi_options` dropdown.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[str | int | bool | float, Field(title='Value')]
    label: Annotated[str, Field(title='Label')]
    description: Annotated[str | None, Field(title='Description')] = None


class PropertyType(Enum):
    """
    Bounded vocabulary of property types the renderer dispatches on.

    Adding a value here requires a matching arm in the frontend
    `<PropertyInput>` switch and (where relevant) the SDK codegen template.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    options = 'options'
    multi_options = 'multi_options'
    fixed_collection = 'fixed_collection'
    json = 'json'
    tool_refs = 'tool_refs'
    document_refs = 'document_refs'
    recording_ref = 'recording_ref'
    credential_ref = 'credential_ref'
    mention_textarea = 'mention_textarea'
    url = 'url'


class ProviderSyncStatus(BaseModel):
    """
    Result of pushing a phone-number change to the upstream provider.

    Returned alongside create/update responses when the route attempted to
    sync inbound webhook configuration. ``ok=False`` is a warning, not a
    fatal error — the DB write succeeded.
    """

    ok: Annotated[bool, Field(title='Ok')]
    message: Annotated[str | None, Field(title='Message')] = None


class RecordingCreateRequestSchema(BaseModel):
    """
    Request schema for creating a recording record after upload.
    """

    recording_id: Annotated[str, Field(title='Recording Id')]
    """
    Short recording ID from upload step
    """
    tts_provider: Annotated[str | None, Field(title='Tts Provider')] = None
    """
    TTS provider (e.g. elevenlabs)
    """
    tts_model: Annotated[str | None, Field(title='Tts Model')] = None
    """
    TTS model name
    """
    tts_voice_id: Annotated[str | None, Field(title='Tts Voice Id')] = None
    """
    TTS voice identifier
    """
    transcript: Annotated[str, Field(title='Transcript')]
    """
    User-provided transcript of the recording
    """
    storage_key: Annotated[str, Field(title='Storage Key')]
    """
    Storage key from upload step
    """
    metadata: Annotated[dict[str, Any] | None, Field(title='Metadata')] = None
    """
    Optional metadata (file_size, duration, etc.)
    """


class RecordingResponseSchema(BaseModel):
    """
    Response schema for a single recording.
    """

    id: Annotated[int, Field(title='Id')]
    recording_id: Annotated[str, Field(title='Recording Id')]
    workflow_id: Annotated[int | None, Field(title='Workflow Id')] = None
    organization_id: Annotated[int, Field(title='Organization Id')]
    tts_provider: Annotated[str | None, Field(title='Tts Provider')] = None
    tts_model: Annotated[str | None, Field(title='Tts Model')] = None
    tts_voice_id: Annotated[str | None, Field(title='Tts Voice Id')] = None
    transcript: Annotated[str, Field(title='Transcript')]
    storage_key: Annotated[str, Field(title='Storage Key')]
    storage_backend: Annotated[str, Field(title='Storage Backend')]
    metadata: Annotated[dict[str, Any], Field(title='Metadata')]
    created_by: Annotated[int, Field(title='Created By')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    is_active: Annotated[bool, Field(title='Is Active')]


class RecordingUpdateRequestSchema(BaseModel):
    """
    Request schema for updating a recording's ID.
    """

    recording_id: Annotated[
        str,
        Field(
            max_length=64,
            min_length=1,
            pattern='^[a-zA-Z0-9_-]+$',
            title='Recording Id',
        ),
    ]
    """
    New descriptive recording ID (letters, numbers, hyphens, underscores only)
    """


class RecordingUploadResponseSchema(BaseModel):
    """
    Response schema with presigned upload URL.
    """

    upload_url: Annotated[str, Field(title='Upload Url')]
    """
    Presigned URL for uploading the audio
    """
    recording_id: Annotated[str, Field(title='Recording Id')]
    """
    Short unique recording ID
    """
    storage_key: Annotated[str, Field(title='Storage Key')]
    """
    Storage key where file will be uploaded
    """


class Name(RootModel[str]):
    root: Annotated[str, Field(max_length=255, min_length=1, title='Name')]
    """
    Name for the redial campaign
    """


class RetryConfigRequest(BaseModel):
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    max_retries: Annotated[int | None, Field(ge=0, le=10, title='Max Retries')] = 2
    retry_delay_seconds: Annotated[
        int | None, Field(ge=30, le=3600, title='Retry Delay Seconds')
    ] = 120
    retry_on_busy: Annotated[bool | None, Field(title='Retry On Busy')] = True
    retry_on_no_answer: Annotated[bool | None, Field(title='Retry On No Answer')] = True
    retry_on_voicemail: Annotated[bool | None, Field(title='Retry On Voicemail')] = True


class RetryConfigResponse(BaseModel):
    enabled: Annotated[bool, Field(title='Enabled')]
    max_retries: Annotated[int, Field(title='Max Retries')]
    retry_delay_seconds: Annotated[int, Field(title='Retry Delay Seconds')]
    retry_on_busy: Annotated[bool, Field(title='Retry On Busy')]
    retry_on_no_answer: Annotated[bool, Field(title='Retry On No Answer')]
    retry_on_voicemail: Annotated[bool, Field(title='Retry On Voicemail')]


class TelephonyConfigurationDetail(BaseModel):
    """
    Body of ``GET /telephony-configs/{id}`` — credentials are masked.
    """

    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    provider: Annotated[str, Field(title='Provider')]
    is_default_outbound: Annotated[bool, Field(title='Is Default Outbound')]
    credentials: Annotated[dict[str, Any], Field(title='Credentials')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class TelephonyConfigurationListItem(BaseModel):
    """
    One row in ``GET /telephony-configs``.
    """

    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    provider: Annotated[str, Field(title='Provider')]
    is_default_outbound: Annotated[bool, Field(title='Is Default Outbound')]
    phone_number_count: Annotated[int | None, Field(title='Phone Number Count')] = 0
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]


class TelephonyConfigurationListResponse(BaseModel):
    configurations: Annotated[
        list[TelephonyConfigurationListItem], Field(title='Configurations')
    ]


class TelnyxConfigurationRequest(BaseModel):
    """
    Request schema for Telnyx configuration.
    """

    provider: Annotated[Literal['telnyx'], Field(title='Provider')] = 'telnyx'
    api_key: Annotated[str, Field(title='Api Key')]
    """
    Telnyx API Key
    """
    connection_id: Annotated[str | None, Field(title='Connection Id')] = None
    """
    Telnyx Call Control Application ID (connection_id). If omitted, a Call Control Application is auto-created on save and its id is stored on the configuration.
    """
    webhook_public_key: Annotated[str | None, Field(title='Webhook Public Key')] = None
    """
    Webhook public key from Mission Control Portal → Keys & Credentials → Public Key. Used to verify Telnyx webhook signatures.
    """
    from_numbers: Annotated[list[str] | None, Field(title='From Numbers')] = None
    """
    List of Telnyx phone numbers
    """


class TimeSlotRequest(BaseModel):
    day_of_week: Annotated[int, Field(ge=0, le=6, title='Day Of Week')]
    start_time: Annotated[str, Field(pattern='^\\d{2}:\\d{2}$', title='Start Time')]
    end_time: Annotated[str, Field(pattern='^\\d{2}:\\d{2}$', title='End Time')]


class TimeSlotResponse(BaseModel):
    day_of_week: Annotated[int, Field(title='Day Of Week')]
    start_time: Annotated[str, Field(title='Start Time')]
    end_time: Annotated[str, Field(title='End Time')]


class ToolParameter(BaseModel):
    """
    A parameter that the tool accepts.
    """

    name: Annotated[str, Field(title='Name')]
    """
    Parameter name (used as key in request body)
    """
    type: Annotated[str, Field(title='Type')]
    """
    Parameter type: string, number, or boolean
    """
    description: Annotated[str, Field(title='Description')]
    """
    Description of what this parameter is for
    """
    required: Annotated[bool | None, Field(title='Required')] = True
    """
    Whether this parameter is required
    """


class ToolResponse(BaseModel):
    """
    Response schema for a tool.
    """

    id: Annotated[int, Field(title='Id')]
    tool_uuid: Annotated[str, Field(title='Tool Uuid')]
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')]
    category: Annotated[str, Field(title='Category')]
    icon: Annotated[str | None, Field(title='Icon')]
    icon_color: Annotated[str | None, Field(title='Icon Color')]
    status: Annotated[str, Field(title='Status')]
    definition: Annotated[dict[str, Any], Field(title='Definition')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime | None, Field(title='Updated At')]
    created_by: CreatedByResponse | None = None


class MessageType1(Enum):
    """
    Type of message to play before transfer
    """

    none = 'none'
    custom = 'custom'
    audio = 'audio'


class TransferCallConfig(BaseModel):
    """
    Configuration for Transfer Call tools.
    """

    destination: Annotated[str, Field(title='Destination')]
    """
    Phone number or SIP endpoint to transfer the call to (E.164 format e.g., +1234567890, or SIP endpoint e.g., PJSIP/1234)
    """
    messageType: Annotated[MessageType1 | None, Field(title='Messagetype')] = 'none'
    """
    Type of message to play before transfer
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before transferring the call
    """
    audioRecordingId: Annotated[str | None, Field(title='Audiorecordingid')] = None
    """
    Recording ID for audio message before transfer
    """
    timeout: Annotated[int | None, Field(ge=5, le=120, title='Timeout')] = 30
    """
    Maximum time in seconds to wait for destination to answer (5-120 seconds)
    """


class TransferCallToolDefinition(BaseModel):
    """
    Tool definition for Transfer Call tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version
    """
    type: Annotated[Literal['transfer_call'], Field(title='Type')]
    """
    Tool type
    """
    config: TransferCallConfig
    """
    Transfer Call configuration
    """


class TwilioConfigurationRequest(BaseModel):
    """
    Request schema for Twilio configuration.
    """

    provider: Annotated[Literal['twilio'], Field(title='Provider')] = 'twilio'
    account_sid: Annotated[str, Field(title='Account Sid')]
    """
    Twilio Account SID
    """
    auth_token: Annotated[str, Field(title='Auth Token')]
    """
    Twilio Auth Token
    """
    from_numbers: Annotated[list[str] | None, Field(title='From Numbers')] = None
    """
    List of Twilio phone numbers
    """


class Name1(RootModel[str]):
    root: Annotated[str, Field(max_length=255, min_length=1, title='Name')]


class Name2(RootModel[str]):
    root: Annotated[str, Field(max_length=255, title='Name')]


class Icon1(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Icon')]


class IconColor1(RootModel[str]):
    root: Annotated[str, Field(max_length=7, title='Icon Color')]


class UpdateWorkflowRequest(BaseModel):
    name: Annotated[str | None, Field(title='Name')] = None
    workflow_definition: Annotated[
        dict[str, Any] | None, Field(title='Workflow Definition')
    ] = None
    template_context_variables: Annotated[
        dict[str, Any] | None, Field(title='Template Context Variables')
    ] = None
    workflow_configurations: Annotated[
        dict[str, Any] | None, Field(title='Workflow Configurations')
    ] = None


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]
    input: Annotated[Any | None, Field(title='Input')] = None
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None


class VobizConfigurationRequest(BaseModel):
    """
    Request schema for Vobiz configuration.
    """

    provider: Annotated[Literal['vobiz'], Field(title='Provider')] = 'vobiz'
    auth_id: Annotated[str, Field(title='Auth Id')]
    """
    Vobiz Account ID (e.g., MA_SYQRLN1K)
    """
    auth_token: Annotated[str, Field(title='Auth Token')]
    """
    Vobiz Auth Token
    """
    application_id: Annotated[str | None, Field(title='Application Id')] = None
    """
    Vobiz Application ID. The application's answer_url is updated when inbound workflows are attached to numbers on this account. If omitted, an application is auto-created on save and its id is stored on the configuration.
    """
    from_numbers: Annotated[list[str] | None, Field(title='From Numbers')] = None
    """
    List of Vobiz phone numbers (E.164 without + prefix)
    """


class VonageConfigurationRequest(BaseModel):
    """
    Request schema for Vonage configuration.
    """

    provider: Annotated[Literal['vonage'], Field(title='Provider')] = 'vonage'
    api_key: Annotated[str, Field(title='Api Key')]
    """
    Vonage API Key
    """
    api_secret: Annotated[str, Field(title='Api Secret')]
    """
    Vonage API Secret
    """
    application_id: Annotated[str, Field(title='Application Id')]
    """
    Vonage Application ID
    """
    private_key: Annotated[str, Field(title='Private Key')]
    """
    Private key for JWT generation
    """
    from_numbers: Annotated[list[str] | None, Field(title='From Numbers')] = None
    """
    List of Vonage phone numbers (without + prefix)
    """


class WorkflowListResponse(BaseModel):
    """
    Lightweight response for workflow listings (excludes large fields).
    """

    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    status: Annotated[str, Field(title='Status')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    total_runs: Annotated[int, Field(title='Total Runs')]


class WorkflowResponse(BaseModel):
    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    status: Annotated[str, Field(title='Status')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    workflow_definition: Annotated[dict[str, Any], Field(title='Workflow Definition')]
    current_definition_id: Annotated[int | None, Field(title='Current Definition Id')]
    template_context_variables: Annotated[
        dict[str, Any] | None, Field(title='Template Context Variables')
    ] = None
    call_disposition_codes: CallDispositionCodes | None = None
    total_runs: Annotated[int | None, Field(title='Total Runs')] = None
    workflow_configurations: Annotated[
        dict[str, Any] | None, Field(title='Workflow Configurations')
    ] = None
    version_number: Annotated[int | None, Field(title='Version Number')] = None
    version_status: Annotated[str | None, Field(title='Version Status')] = None
    workflow_uuid: Annotated[str | None, Field(title='Workflow Uuid')] = None


class WorkflowRunDetail(BaseModel):
    phone_number: Annotated[str, Field(title='Phone Number')]
    disposition: Annotated[str, Field(title='Disposition')]
    duration_seconds: Annotated[float, Field(title='Duration Seconds')]
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    run_id: Annotated[int, Field(title='Run Id')]
    workflow_name: Annotated[str, Field(title='Workflow Name')]
    created_at: Annotated[str, Field(title='Created At')]


class BatchRecordingCreateRequestSchema(BaseModel):
    """
    Request schema for creating one or more recording records after upload.
    """

    recordings: Annotated[
        list[RecordingCreateRequestSchema],
        Field(max_length=20, min_length=1, title='Recordings'),
    ]
    """
    List of recordings to create
    """


class BatchRecordingCreateResponseSchema(BaseModel):
    """
    Response schema for recording creation.
    """

    recordings: Annotated[list[RecordingResponseSchema], Field(title='Recordings')]
    """
    Created recording records
    """


class BatchRecordingUploadRequestSchema(BaseModel):
    """
    Request schema for getting presigned upload URLs for one or more files.
    """

    files: Annotated[
        list[FileDescriptor], Field(max_length=20, min_length=1, title='Files')
    ]
    """
    List of files to upload
    """


class BatchRecordingUploadResponseSchema(BaseModel):
    """
    Response schema with presigned upload URLs.
    """

    items: Annotated[list[RecordingUploadResponseSchema], Field(title='Items')]
    """
    Upload URLs for each file
    """


class DocumentListResponseSchema(BaseModel):
    """
    Response schema for list of documents.
    """

    documents: Annotated[list[DocumentResponseSchema], Field(title='Documents')]
    total: Annotated[int, Field(title='Total')]
    limit: Annotated[int, Field(title='Limit')]
    offset: Annotated[int, Field(title='Offset')]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class HttpApiConfig(BaseModel):
    """
    Configuration for HTTP API tools.
    """

    method: Annotated[str, Field(title='Method')]
    """
    HTTP method (GET, POST, PUT, PATCH, DELETE)
    """
    url: Annotated[str, Field(title='Url')]
    """
    Target URL
    """
    headers: Annotated[dict[str, str] | None, Field(title='Headers')] = None
    """
    Static headers to include
    """
    credential_uuid: Annotated[str | None, Field(title='Credential Uuid')] = None
    """
    Reference to ExternalCredentialModel for auth
    """
    parameters: Annotated[list[ToolParameter] | None, Field(title='Parameters')] = None
    """
    Parameters that the tool accepts from LLM
    """
    timeout_ms: Annotated[int | None, Field(title='Timeout Ms')] = 5000
    """
    Request timeout in milliseconds
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play after tool execution
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message: text or audio
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for audio custom message
    """


class HttpApiToolDefinition(BaseModel):
    """
    Tool definition for HTTP API tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version
    """
    type: Annotated[Literal['http_api'], Field(title='Type')]
    """
    Tool type
    """
    config: HttpApiConfig
    """
    HTTP API configuration
    """


class PhoneNumberResponse(BaseModel):
    id: Annotated[int, Field(title='Id')]
    telephony_configuration_id: Annotated[
        int, Field(title='Telephony Configuration Id')
    ]
    address: Annotated[str, Field(title='Address')]
    address_normalized: Annotated[str, Field(title='Address Normalized')]
    address_type: Annotated[str, Field(title='Address Type')]
    country_code: Annotated[str | None, Field(title='Country Code')] = None
    label: Annotated[str | None, Field(title='Label')] = None
    inbound_workflow_id: Annotated[int | None, Field(title='Inbound Workflow Id')] = (
        None
    )
    inbound_workflow_name: Annotated[
        str | None, Field(title='Inbound Workflow Name')
    ] = None
    is_active: Annotated[bool, Field(title='Is Active')]
    is_default_caller_id: Annotated[bool, Field(title='Is Default Caller Id')]
    extra_metadata: Annotated[dict[str, Any], Field(title='Extra Metadata')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    provider_sync: ProviderSyncStatus | None = None


class PropertySpec(BaseModel):
    """
    Single field on a node.

    `description` is HUMAN-FACING — shown under the field in the edit
    dialog. Keep it concise and explain what the field does.

    `llm_hint` is LLM-FACING — appears only in the `get_node_type` MCP
    response and in SDK schema output. Use it for catalog tool references
    (e.g., "Use `list_recordings`"), array shape, expected value idioms,
    or anything that would be noise in the UI. Optional; omit when the
    `description` already suffices for both audiences.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    type: PropertyType
    display_name: Annotated[str, Field(title='Display Name')]
    description: Annotated[str, Field(min_length=1, title='Description')]
    """
    Human-facing explanation shown in the UI.
    """
    llm_hint: Annotated[str | None, Field(title='Llm Hint')] = None
    """
    LLM-only guidance; omitted from the UI.
    """
    default: Annotated[Any | None, Field(title='Default')] = None
    required: Annotated[bool | None, Field(title='Required')] = False
    placeholder: Annotated[str | None, Field(title='Placeholder')] = None
    display_options: DisplayOptions | None = None
    options: Annotated[list[PropertyOption] | None, Field(title='Options')] = None
    properties: Annotated[list[PropertySpec] | None, Field(title='Properties')] = None
    min_value: Annotated[float | None, Field(title='Min Value')] = None
    max_value: Annotated[float | None, Field(title='Max Value')] = None
    min_length: Annotated[int | None, Field(title='Min Length')] = None
    max_length: Annotated[int | None, Field(title='Max Length')] = None
    pattern: Annotated[str | None, Field(title='Pattern')] = None
    editor: Annotated[str | None, Field(title='Editor')] = None
    extra: Annotated[dict[str, Any] | None, Field(title='Extra')] = None


class RecordingListResponseSchema(BaseModel):
    """
    Response schema for list of recordings.
    """

    recordings: Annotated[list[RecordingResponseSchema], Field(title='Recordings')]
    total: Annotated[int, Field(title='Total')]


class RedialCampaignRequest(BaseModel):
    name: Annotated[Name | None, Field(title='Name')] = None
    """
    Name for the redial campaign
    """
    retry_on_voicemail: Annotated[bool | None, Field(title='Retry On Voicemail')] = True
    retry_on_no_answer: Annotated[bool | None, Field(title='Retry On No Answer')] = True
    retry_on_busy: Annotated[bool | None, Field(title='Retry On Busy')] = True
    retry_config: RetryConfigRequest | None = None


class ScheduleConfigRequest(BaseModel):
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    timezone: Annotated[str | None, Field(title='Timezone')] = 'UTC'
    slots: Annotated[
        list[TimeSlotRequest], Field(max_length=50, min_length=1, title='Slots')
    ]


class ScheduleConfigResponse(BaseModel):
    enabled: Annotated[bool, Field(title='Enabled')]
    timezone: Annotated[str, Field(title='Timezone')]
    slots: Annotated[list[TimeSlotResponse], Field(title='Slots')]


class TelephonyConfigurationCreateRequest(BaseModel):
    """
    Body for ``POST /telephony-configs``.

    ``config`` carries the provider-specific credential fields (the same
    discriminated union used by the legacy single-config endpoint). Any
    ``from_numbers`` on the inner config are ignored — phone numbers are
    managed via the dedicated phone-numbers endpoints.
    """

    name: Annotated[str, Field(max_length=64, min_length=1, title='Name')]
    is_default_outbound: Annotated[bool | None, Field(title='Is Default Outbound')] = (
        False
    )
    config: Annotated[
        ARIConfigurationRequest
        | CloudonixConfigurationRequest
        | PlivoConfigurationRequest
        | TelnyxConfigurationRequest
        | TwilioConfigurationRequest
        | VobizConfigurationRequest
        | VonageConfigurationRequest,
        Field(discriminator='provider', title='Config'),
    ]


class UpdateCampaignRequest(BaseModel):
    name: Annotated[Name1 | None, Field(title='Name')] = None
    retry_config: RetryConfigRequest | None = None
    max_concurrency: Annotated[
        MaxConcurrency | None, Field(title='Max Concurrency')
    ] = None
    schedule_config: ScheduleConfigRequest | None = None
    circuit_breaker: CircuitBreakerConfigRequest | None = None


class UpdateToolRequest(BaseModel):
    """
    Request schema for updating a tool.
    """

    name: Annotated[Name2 | None, Field(title='Name')] = None
    description: Annotated[str | None, Field(title='Description')] = None
    icon: Annotated[Icon1 | None, Field(title='Icon')] = None
    icon_color: Annotated[IconColor1 | None, Field(title='Icon Color')] = None
    definition: Annotated[
        HttpApiToolDefinition
        | EndCallToolDefinition
        | TransferCallToolDefinition
        | CalculatorToolDefinition
        | None,
        Field(title='Definition'),
    ] = None
    status: Annotated[str | None, Field(title='Status')] = None


class CampaignResponse(BaseModel):
    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    workflow_name: Annotated[str, Field(title='Workflow Name')]
    state: Annotated[str, Field(title='State')]
    source_type: Annotated[str, Field(title='Source Type')]
    source_id: Annotated[str, Field(title='Source Id')]
    total_rows: Annotated[int | None, Field(title='Total Rows')]
    processed_rows: Annotated[int, Field(title='Processed Rows')]
    failed_rows: Annotated[int, Field(title='Failed Rows')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    started_at: Annotated[AwareDatetime | None, Field(title='Started At')]
    completed_at: Annotated[AwareDatetime | None, Field(title='Completed At')]
    retry_config: RetryConfigResponse
    max_concurrency: Annotated[int | None, Field(title='Max Concurrency')] = None
    schedule_config: ScheduleConfigResponse | None = None
    circuit_breaker: CircuitBreakerConfigResponse | None = None
    executed_count: Annotated[int | None, Field(title='Executed Count')] = 0
    total_queued_count: Annotated[int | None, Field(title='Total Queued Count')] = 0
    parent_campaign_id: Annotated[int | None, Field(title='Parent Campaign Id')] = None
    redialed_campaign_id: Annotated[int | None, Field(title='Redialed Campaign Id')] = (
        None
    )
    telephony_configuration_id: Annotated[
        int | None, Field(title='Telephony Configuration Id')
    ] = None
    telephony_configuration_name: Annotated[
        str | None, Field(title='Telephony Configuration Name')
    ] = None
    logs: Annotated[list[CampaignLogEntryResponse] | None, Field(title='Logs')] = None


class CampaignsResponse(BaseModel):
    campaigns: Annotated[list[CampaignResponse], Field(title='Campaigns')]


class CreateCampaignRequest(BaseModel):
    name: Annotated[str, Field(max_length=255, min_length=1, title='Name')]
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    source_type: Annotated[
        str, Field(pattern='^(google-sheet|csv)$', title='Source Type')
    ]
    source_id: Annotated[str, Field(title='Source Id')]
    telephony_configuration_id: Annotated[
        int | None, Field(title='Telephony Configuration Id')
    ] = None
    retry_config: RetryConfigRequest | None = None
    max_concurrency: Annotated[
        MaxConcurrency | None, Field(title='Max Concurrency')
    ] = None
    schedule_config: ScheduleConfigRequest | None = None
    circuit_breaker: CircuitBreakerConfigRequest | None = None


class CreateToolRequest(BaseModel):
    """
    Request schema for creating a tool.
    """

    name: Annotated[str, Field(max_length=255, title='Name')]
    description: Annotated[str | None, Field(title='Description')] = None
    category: Annotated[str | None, Field(title='Category')] = 'http_api'
    icon: Annotated[Icon | None, Field(title='Icon', validate_default=True)] = 'globe'
    icon_color: Annotated[
        IconColor | None, Field(title='Icon Color', validate_default=True)
    ] = '#3B82F6'
    definition: Annotated[
        HttpApiToolDefinition
        | EndCallToolDefinition
        | TransferCallToolDefinition
        | CalculatorToolDefinition,
        Field(discriminator='type', title='Definition'),
    ]


class NodeSpec(BaseModel):
    """
    Single source of truth for a node type.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    display_name: Annotated[str, Field(title='Display Name')]
    description: Annotated[str, Field(min_length=1, title='Description')]
    """
    Human-facing explanation shown in AddNodePanel.
    """
    llm_hint: Annotated[str | None, Field(title='Llm Hint')] = None
    """
    LLM-only guidance; omitted from the UI.
    """
    category: NodeCategory
    icon: Annotated[str, Field(title='Icon')]
    version: Annotated[str | None, Field(title='Version')] = '1.0.0'
    properties: Annotated[list[PropertySpec], Field(title='Properties')]
    examples: Annotated[list[NodeExample] | None, Field(title='Examples')] = None
    graph_constraints: GraphConstraints | None = None


class NodeTypesResponse(BaseModel):
    spec_version: Annotated[str, Field(title='Spec Version')]
    node_types: Annotated[list[NodeSpec], Field(title='Node Types')]


PropertySpec.model_rebuild()
